// FINLIT — Topic Dependency Graph
// Full metadata for all 25 topics: prerequisites, related topics, category, time estimates

const TOPICS = [
  // ── BEGINNER ──────────────────────────────────────────────────────────────
  {
    name: 'Budgeting Basics',
    difficulty: 'beginner',
    category: 'basics',
    prerequisites: [],
    related: ['Tracking Expenses', 'Saving Money', 'Emergency Funds'],
    estimatedMinutes: 8,
    tags: ['budget', 'spending', 'planning', 'foundation'],
  },
  {
    name: 'Saving Money',
    difficulty: 'beginner',
    category: 'basics',
    prerequisites: [],
    related: ['Budgeting Basics', 'Emergency Funds', 'Investing Basics'],
    estimatedMinutes: 7,
    tags: ['savings', 'habits', 'foundation'],
  },
  {
    name: 'Understanding Income',
    difficulty: 'beginner',
    category: 'basics',
    prerequisites: [],
    related: ['Budgeting Basics', 'Tax Fundamentals'],
    estimatedMinutes: 7,
    tags: ['income', 'salary', 'earnings', 'foundation'],
  },
  {
    name: 'Credit vs Debit',
    difficulty: 'beginner',
    category: 'basics',
    prerequisites: [],
    related: ['Credit Scores', 'Debt Management', 'Banking Accounts'],
    estimatedMinutes: 8,
    tags: ['credit', 'debit', 'cards', 'spending'],
  },
  {
    name: 'Emergency Funds',
    difficulty: 'beginner',
    category: 'basics',
    prerequisites: ['Saving Money'],
    related: ['Budgeting Basics', 'Insurance Types'],
    estimatedMinutes: 9,
    tags: ['emergency', 'safety net', 'savings', 'security'],
  },
  {
    name: 'Simple Interest',
    difficulty: 'beginner',
    category: 'basics',
    prerequisites: [],
    related: ['Compound Interest', 'Banking Accounts'],
    estimatedMinutes: 7,
    tags: ['interest', 'math', 'loans', 'savings'],
  },
  {
    name: 'Banking Accounts',
    difficulty: 'beginner',
    category: 'basics',
    prerequisites: [],
    related: ['Saving Money', 'Credit vs Debit', 'Simple Interest'],
    estimatedMinutes: 6,
    tags: ['bank', 'checking', 'savings account', 'foundation'],
  },
  {
    name: 'Tracking Expenses',
    difficulty: 'beginner',
    category: 'basics',
    prerequisites: ['Budgeting Basics'],
    related: ['Budgeting Basics', 'Saving Money'],
    estimatedMinutes: 6,
    tags: ['expenses', 'tracking', 'spending', 'habits'],
  },

  // ── INTERMEDIATE ─────────────────────────────────────────────────────────
  {
    name: 'Compound Interest',
    difficulty: 'intermediate',
    category: 'investing',
    prerequisites: ['Simple Interest'],
    related: ['Simple Interest', 'Investing Basics', 'Retirement Accounts'],
    estimatedMinutes: 10,
    tags: ['compound', 'interest', 'growth', 'time'],
  },
  {
    name: 'Credit Scores',
    difficulty: 'intermediate',
    category: 'debt',
    prerequisites: ['Credit vs Debit'],
    related: ['Credit vs Debit', 'Debt Management'],
    estimatedMinutes: 11,
    tags: ['credit score', 'FICO', 'credit report', 'loans'],
  },
  {
    name: 'Investing Basics',
    difficulty: 'intermediate',
    category: 'investing',
    prerequisites: ['Saving Money'],
    related: ['Saving Money', 'Stocks & Bonds', 'Compound Interest'],
    estimatedMinutes: 12,
    tags: ['investing', 'markets', 'returns', 'wealth'],
  },
  {
    name: 'Stocks & Bonds',
    difficulty: 'intermediate',
    category: 'investing',
    prerequisites: ['Investing Basics'],
    related: ['Investing Basics', 'Portfolio Diversification', 'Risk Management'],
    estimatedMinutes: 13,
    tags: ['stocks', 'bonds', 'equities', 'securities'],
  },
  {
    name: 'Retirement Accounts',
    difficulty: 'intermediate',
    category: 'investing',
    prerequisites: ['Investing Basics'],
    related: ['Investing Basics', 'Tax Fundamentals', 'Compound Interest'],
    estimatedMinutes: 12,
    tags: ['401k', 'IRA', 'retirement', 'long-term'],
  },
  {
    name: 'Tax Fundamentals',
    difficulty: 'intermediate',
    category: 'basics',
    prerequisites: ['Understanding Income'],
    related: ['Understanding Income', 'Tax Optimization', 'Retirement Accounts'],
    estimatedMinutes: 11,
    tags: ['taxes', 'IRS', 'deductions', 'filing'],
  },
  {
    name: 'Debt Management',
    difficulty: 'intermediate',
    category: 'debt',
    prerequisites: ['Credit vs Debit'],
    related: ['Credit Scores', 'Credit vs Debit', 'Budgeting Basics'],
    estimatedMinutes: 11,
    tags: ['debt', 'payoff', 'snowball', 'avalanche'],
  },
  {
    name: 'Insurance Types',
    difficulty: 'intermediate',
    category: 'life',
    prerequisites: [],
    related: ['Emergency Funds', 'Estate Planning', 'Risk Management'],
    estimatedMinutes: 10,
    tags: ['insurance', 'health', 'auto', 'life insurance', 'protection'],
  },
  {
    name: 'Real Estate Basics',
    difficulty: 'intermediate',
    category: 'investing',
    prerequisites: ['Saving Money'],
    related: ['Investing Basics', 'Debt Management'],
    estimatedMinutes: 13,
    tags: ['real estate', 'mortgage', 'property', 'housing'],
  },

  // ── ADVANCED ─────────────────────────────────────────────────────────────
  {
    name: 'Portfolio Diversification',
    difficulty: 'advanced',
    category: 'investing',
    prerequisites: ['Stocks & Bonds', 'Investing Basics'],
    related: ['Stocks & Bonds', 'Asset Allocation', 'Risk Management'],
    estimatedMinutes: 15,
    tags: ['diversification', 'portfolio', 'risk', 'allocation'],
  },
  {
    name: 'Asset Allocation',
    difficulty: 'advanced',
    category: 'investing',
    prerequisites: ['Portfolio Diversification'],
    related: ['Portfolio Diversification', 'Risk Management', 'Alternative Investments'],
    estimatedMinutes: 14,
    tags: ['asset allocation', 'rebalancing', 'portfolio', 'strategy'],
  },
  {
    name: 'Options Trading',
    difficulty: 'advanced',
    category: 'investing',
    prerequisites: ['Stocks & Bonds'],
    related: ['Stocks & Bonds', 'Risk Management'],
    estimatedMinutes: 18,
    tags: ['options', 'derivatives', 'calls', 'puts', 'trading'],
  },
  {
    name: 'Cryptocurrency',
    difficulty: 'advanced',
    category: 'investing',
    prerequisites: ['Investing Basics'],
    related: ['Investing Basics', 'Risk Management', 'Portfolio Diversification'],
    estimatedMinutes: 14,
    tags: ['crypto', 'bitcoin', 'blockchain', 'DeFi'],
  },
  {
    name: 'Tax Optimization',
    difficulty: 'advanced',
    category: 'basics',
    prerequisites: ['Tax Fundamentals'],
    related: ['Tax Fundamentals', 'Retirement Accounts', 'Estate Planning'],
    estimatedMinutes: 14,
    tags: ['tax optimization', 'tax loss harvesting', 'deductions', 'strategy'],
  },
  {
    name: 'Estate Planning',
    difficulty: 'advanced',
    category: 'life',
    prerequisites: ['Insurance Types', 'Tax Fundamentals'],
    related: ['Insurance Types', 'Tax Optimization'],
    estimatedMinutes: 13,
    tags: ['estate', 'will', 'trust', 'inheritance', 'legacy'],
  },
  {
    name: 'Risk Management',
    difficulty: 'advanced',
    category: 'investing',
    prerequisites: ['Portfolio Diversification'],
    related: ['Portfolio Diversification', 'Asset Allocation', 'Insurance Types'],
    estimatedMinutes: 13,
    tags: ['risk', 'volatility', 'hedging', 'protection'],
  },
  {
    name: 'Alternative Investments',
    difficulty: 'advanced',
    category: 'investing',
    prerequisites: ['Portfolio Diversification', 'Asset Allocation'],
    related: ['Asset Allocation', 'Risk Management', 'Cryptocurrency'],
    estimatedMinutes: 15,
    tags: ['alternatives', 'hedge funds', 'commodities', 'REITs', 'private equity'],
  },
];

// All topic names as a flat list for quick lookup
const ALL_TOPIC_NAMES = TOPICS.map(t => t.name);

// Fast lookup by name
const TOPIC_MAP = Object.fromEntries(TOPICS.map(t => [t.name, t]));

module.exports = { TOPICS, ALL_TOPIC_NAMES, TOPIC_MAP };
