// frontend/src/config/badgesConfig.js
// FINLIT — Badge config (Gaming + Fashion).
// All badges are individually pre-processed PNGs — canvas hook passes them through as-is.
// Each badge now includes: category, tier, secret, hintWhenLocked

const INDIV = { batchCols: 1, batchRows: 1, cellCol: 0, cellRow: 0, textRatio: 0, whiteTol: 0 };

const G = (id) => ({ ...INDIV, imagePath: `/BADGES/GAMING/gaming-indiv-${id}.png` });
const F = (id) => ({ ...INDIV, imagePath: `/BADGES/FASHION/fashion-indiv-${id}.png` });

// ── Gaming badges (73 total) ──────────────────────────────────────────────────
export const GAMING_BADGES_CONFIG = [
  // Batch 1 — Progression (12 badges)
  // Tiers: common/common/uncommon/uncommon/uncommon/uncommon/rare/rare/epic/epic/legendary/legendary
  {
    id: 'first_lesson',
    name: 'First Steps',
    ...G('first_lesson'),
    desc: 'Complete your first topic',
    category: 'progression',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Complete your first topic',
  },
  {
    id: 'gaming_tutorial_complete',
    name: 'Tutorial Complete',
    ...G('gaming_tutorial_complete'),
    desc: 'Finish the tutorial',
    category: 'progression',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Finish the tutorial',
  },
  {
    id: 'gaming_resource_master',
    name: 'Resource Master',
    ...G('gaming_resource_master'),
    desc: 'Master your resources',
    category: 'progression',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Master your resources',
  },
  {
    id: 'gaming_vault_keeper',
    name: 'Vault Keeper',
    ...G('gaming_vault_keeper'),
    desc: 'Build your vault',
    category: 'progression',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Build your vault',
  },
  {
    id: 'gaming_wealth_warrior',
    name: 'Wealth Warrior',
    ...G('gaming_wealth_warrior'),
    desc: 'Become a wealth warrior',
    category: 'progression',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Become a wealth warrior',
  },
  {
    id: 'gaming_xp_grinder',
    name: 'XP Grinder',
    ...G('gaming_xp_grinder'),
    desc: 'Grind for XP',
    category: 'progression',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Grind for XP',
  },
  {
    id: 'gaming_strategy_expert',
    name: 'Strategy Expert',
    ...G('gaming_strategy_expert'),
    desc: 'Master financial strategy',
    category: 'progression',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Master financial strategy',
  },
  {
    id: 'gaming_risk_taker',
    name: 'Risk Taker',
    ...G('gaming_risk_taker'),
    desc: 'Take calculated risks',
    category: 'progression',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Take calculated risks',
  },
  {
    id: 'gaming_financial_master',
    name: 'Financial Master',
    ...G('gaming_financial_master'),
    desc: 'Master your finances',
    category: 'progression',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Master your finances',
  },
  {
    id: 'gaming_final_boss',
    name: 'Final Boss Defeated',
    ...G('gaming_final_boss'),
    desc: 'Defeat the final boss',
    category: 'progression',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Defeat the final boss',
  },
  {
    id: 'legendary',
    name: 'Legendary Player',
    ...G('legendary'),
    desc: 'Complete all zones',
    category: 'progression',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Complete all zones',
  },
  {
    id: 'gaming_new_game_plus',
    name: 'New Game+',
    ...G('gaming_new_game_plus'),
    desc: 'Start the journey again',
    category: 'progression',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Start the journey again',
  },

  // Batch 2 — Boss Battles (12 badges)
  // Tiers: common/uncommon/rare/epic/uncommon/rare/epic/rare/rare/epic/rare/legendary
  {
    id: 'gaming_boss_slayer_1',
    name: 'Boss Slayer I',
    ...G('gaming_boss_slayer_1'),
    desc: 'Defeat your first boss',
    category: 'boss_battles',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Defeat your first boss',
  },
  {
    id: 'gaming_boss_slayer_2',
    name: 'Boss Slayer II',
    ...G('gaming_boss_slayer_2'),
    desc: 'Defeat two bosses',
    category: 'boss_battles',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Defeat two bosses',
  },
  {
    id: 'gaming_boss_slayer_3',
    name: 'Boss Slayer III',
    ...G('gaming_boss_slayer_3'),
    desc: 'Defeat three bosses',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Defeat three bosses',
  },
  {
    id: 'gaming_boss_hunter',
    name: 'Boss Hunter',
    ...G('gaming_boss_hunter'),
    desc: 'Hunt down every boss',
    category: 'boss_battles',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Hunt down every boss',
  },
  {
    id: 'gaming_island_champ',
    name: 'Tutorial Island Champion',
    ...G('gaming_island_champ'),
    desc: 'Champion of Tutorial Island',
    category: 'boss_battles',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Champion of Tutorial Island',
  },
  {
    id: 'gaming_main_quest',
    name: 'Main Quest Victor',
    ...G('gaming_main_quest'),
    desc: 'Complete the main quest',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Complete the main quest',
  },
  {
    id: 'gaming_endgame',
    name: 'Endgame Conqueror',
    ...G('gaming_endgame'),
    desc: 'Conquer the endgame',
    category: 'boss_battles',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Conquer the endgame',
  },
  {
    id: 'gaming_raid_leader',
    name: 'Raid Leader',
    ...G('gaming_raid_leader'),
    desc: 'Lead the raid',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Lead the raid',
  },
  {
    id: 'gaming_dragon_slayer',
    name: 'Dragon Slayer',
    ...G('gaming_dragon_slayer'),
    desc: 'Slay the dragon',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Slay the dragon',
  },
  {
    id: 'gaming_flawless',
    name: 'Flawless Victory',
    ...G('gaming_flawless'),
    desc: 'Win without a single loss',
    category: 'boss_battles',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Win without a single loss',
  },
  {
    id: 'gaming_speed_runner',
    name: 'Speed Runner',
    ...G('gaming_speed_runner'),
    desc: 'Complete the run fast',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Complete the run fast',
  },
  {
    id: 'gaming_platinum_trophy',
    name: 'Platinum Trophy',
    ...G('gaming_platinum_trophy'),
    desc: 'Achieve platinum status',
    category: 'boss_battles',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Achieve platinum status',
  },

  // Batch 3 — Mastery (10 badges)
  // Tiers: common/uncommon/rare/epic/legendary/uncommon/rare/epic/epic/legendary
  {
    id: 'gaming_skill_unlocked',
    name: 'Skill Unlocked',
    ...G('gaming_skill_unlocked'),
    desc: 'Unlock your first skill',
    category: 'mastery',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'gaming_skill_collector',
    name: 'Skill Collector',
    ...G('gaming_skill_collector'),
    desc: 'Collect multiple skills',
    category: 'mastery',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'gaming_skill_master',
    name: 'Skill Master',
    ...G('gaming_skill_master'),
    desc: 'Master all skills',
    category: 'mastery',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'gaming_full_arsenal',
    name: 'Full Arsenal',
    ...G('gaming_full_arsenal'),
    desc: 'Complete your arsenal',
    category: 'mastery',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'gaming_god_tier',
    name: 'God-Tier Player',
    ...G('gaming_god_tier'),
    desc: 'Reach god-tier status',
    category: 'mastery',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'perfect_quiz',
    name: 'Perfect Play',
    ...G('perfect_quiz'),
    desc: 'Get 5/5 on a quiz',
    category: 'mastery',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'gaming_clutch',
    name: 'Clutch Player',
    ...G('gaming_clutch'),
    desc: 'Win in clutch moments',
    category: 'mastery',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'gaming_unstoppable',
    name: 'Unstoppable',
    ...G('gaming_unstoppable'),
    desc: 'Become unstoppable',
    category: 'mastery',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'gaming_no_deaths',
    name: 'No Deaths',
    ...G('gaming_no_deaths'),
    desc: 'Complete without failing',
    category: 'mastery',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'gaming_plat_master',
    name: 'Platinum Master',
    ...G('gaming_plat_master'),
    desc: 'Another platinum milestone',
    category: 'mastery',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },

  // Batch 4 — Streaks (10 badges)
  // Tiers: common/uncommon/rare/epic/legendary/common/uncommon/rare/epic/legendary
  {
    id: 'streak_3',
    name: 'Getting Started',
    ...G('streak_3'),
    desc: 'Learn 3 days in a row',
    category: 'streaks',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'streak_7',
    name: 'Dedicated Gamer',
    ...G('streak_7'),
    desc: '7-day learning streak',
    category: 'streaks',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'gaming_grinder',
    name: 'Hardcore Grinder',
    ...G('gaming_grinder'),
    desc: 'Grind for 14 days',
    category: 'streaks',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'gaming_no_life',
    name: 'No Life Mode',
    ...G('gaming_no_life'),
    desc: '30-day streak',
    category: 'streaks',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'gaming_eternal',
    name: 'Eternal Grind',
    ...G('gaming_eternal'),
    desc: '100-day streak',
    category: 'streaks',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'level_5',
    name: 'Leveling Up',
    ...G('level_5'),
    desc: 'Reach level 5',
    category: 'streaks',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'gaming_power_level',
    name: 'Power Leveler',
    ...G('gaming_power_level'),
    desc: 'Earn 1000 XP',
    category: 'streaks',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'gaming_endgame_xp',
    name: 'Endgame Stats',
    ...G('gaming_endgame_xp'),
    desc: 'Earn 2000 XP',
    category: 'streaks',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'gaming_max_level',
    name: 'Max Level',
    ...G('gaming_max_level'),
    desc: 'Reach the XP cap',
    category: 'streaks',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'gaming_xp_god',
    name: 'XP God',
    ...G('gaming_xp_god'),
    desc: 'Become the XP god',
    category: 'streaks',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },

  // Batch 5 — Special (16 gaming badges)
  // Tiers: uncommon/uncommon/rare/rare/uncommon/common/uncommon/uncommon/common/rare/uncommon/rare/epic/uncommon/rare/rare
  {
    id: 'gaming_speed_demon',
    name: 'Speed Demon',
    ...G('gaming_speed_demon'),
    desc: 'Complete topics fast',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_marathon',
    name: 'Marathon Runner',
    ...G('gaming_marathon'),
    desc: 'Long study sessions',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_speedrun',
    name: 'Speedrun King',
    ...G('gaming_speedrun'),
    desc: 'Complete all in record time',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_one_shot',
    name: 'One-Shot Wonder',
    ...G('gaming_one_shot'),
    desc: 'Pass quiz on first try',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_maintained',
    name: 'Well-Maintained',
    ...G('gaming_maintained'),
    desc: 'No skill decay for 30 days',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_practice',
    name: 'Practice Makes Perfect',
    ...G('gaming_practice'),
    desc: 'Review topics multiple times',
    category: 'special',
    tier: 'common',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_sharpener',
    name: 'Skill Sharpener',
    ...G('gaming_sharpener'),
    desc: 'Sharpen your skills',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_healer',
    name: 'Character Healer',
    ...G('gaming_healer'),
    desc: 'Recover from losses',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_explorer',
    name: 'Explorer',
    ...G('gaming_explorer'),
    desc: 'Explore all areas',
    category: 'special',
    tier: 'common',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'topic_master',
    name: 'Completionist',
    ...G('topic_master'),
    desc: 'Complete 10 topics',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_achievement',
    name: 'Achievement Hunter',
    ...G('gaming_achievement'),
    desc: 'Unlock many achievements',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_badge_collect',
    name: 'Badge Collector',
    ...G('gaming_badge_collect'),
    desc: 'Collect all badges',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_chosen_one',
    name: 'The Chosen One',
    ...G('gaming_chosen_one'),
    desc: 'Fulfill your destiny',
    category: 'special',
    tier: 'epic',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_helpful_guide',
    name: 'Helpful Guide',
    ...G('gaming_helpful_guide'),
    desc: 'Guide others to success',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_deep_thinker',
    name: 'Deep Thinker',
    ...G('gaming_deep_thinker'),
    desc: 'Think deeply about finance',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'gaming_adaptive',
    name: 'Adaptive Learner',
    ...G('gaming_adaptive'),
    desc: 'Adapt your learning style',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },

  // Batch 6 — Elite (5 badges) — all legendary
  {
    id: 'gaming_true_gamer',
    name: 'True Gamer',
    ...G('gaming_true_gamer'),
    desc: 'A true gaming veteran',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'A true gaming veteran',
  },
  {
    id: 'gaming_hardcore',
    name: 'Hardcore Mode',
    ...G('gaming_hardcore'),
    desc: 'Enable hardcore mode',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Enable hardcore mode',
  },
  {
    id: 'gaming_legendary_diff',
    name: 'Legendary Difficulty',
    ...G('gaming_legendary_diff'),
    desc: 'Complete on legendary',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Complete on legendary',
  },
  {
    id: 'gaming_insane',
    name: 'Insane Mode',
    ...G('gaming_insane'),
    desc: 'Complete on insane',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Complete on insane',
  },
  {
    id: 'gaming_impossible',
    name: 'Impossible Achievement',
    ...G('gaming_impossible'),
    desc: 'The ultimate achievement',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'The ultimate achievement',
  },

  // Batch 7 — Secret (8 badges)
  // Tiers: legendary/rare/rare/uncommon/rare/epic/legendary/epic
  {
    id: 'gaming_chosen_special',
    name: 'The Chosen One',
    ...G('gaming_chosen_special'),
    desc: 'A special destiny awaits',
    category: 'secret',
    tier: 'legendary',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'gaming_night_owl',
    name: 'Night Owl',
    ...G('gaming_night_owl'),
    desc: 'Study late at night',
    category: 'secret',
    tier: 'rare',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'gaming_early_bird',
    name: 'Early Bird',
    ...G('gaming_early_bird'),
    desc: 'Study early in the morning',
    category: 'secret',
    tier: 'rare',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'gaming_weekend',
    name: 'Weekend Warrior',
    ...G('gaming_weekend'),
    desc: 'Study on weekends',
    category: 'secret',
    tier: 'uncommon',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'gaming_comeback',
    name: 'Comeback King',
    ...G('gaming_comeback'),
    desc: 'Return after a long break',
    category: 'secret',
    tier: 'rare',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'gaming_perfectionist',
    name: 'Perfectionist',
    ...G('gaming_perfectionist'),
    desc: 'Perfect scores across all topics',
    category: 'secret',
    tier: 'epic',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'gaming_finns_fav',
    name: "FINN's Favorite",
    ...G('gaming_finns_fav'),
    desc: 'FINN approves of you',
    category: 'secret',
    tier: 'legendary',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'gaming_dedication',
    name: 'True Dedication',
    ...G('gaming_dedication'),
    desc: '100 sessions completed',
    category: 'secret',
    tier: 'epic',
    secret: true,
    hintWhenLocked: null,
  },
];

// ── Fashion badges (75 total) ─────────────────────────────────────────────────
export const FASHION_BADGES_CONFIG = [
  // Batch 1 — Progression (12 badges)
  // Tiers: common/common/uncommon/uncommon/uncommon/uncommon/rare/rare/epic/epic/legendary/legendary
  {
    id: 'fashion_first_look',
    name: 'First Look',
    ...F('fashion_first_look'),
    desc: 'Complete your first topic',
    category: 'progression',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Complete your first topic',
  },
  {
    id: 'fashion_boutique_graduate',
    name: 'Boutique Graduate',
    ...F('fashion_boutique_graduate'),
    desc: 'Graduate from the boutique',
    category: 'progression',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Graduate from the boutique',
  },
  {
    id: 'fashion_budget_stylist',
    name: 'Budget Stylist',
    ...F('fashion_budget_stylist'),
    desc: 'Style on a budget',
    category: 'progression',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Style on a budget',
  },
  {
    id: 'fashion_savings_curator',
    name: 'Savings Curator',
    ...F('fashion_savings_curator'),
    desc: 'Curate your savings',
    category: 'progression',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Curate your savings',
  },
  {
    id: 'fashion_atelier_artisan',
    name: 'Atelier Artisan',
    ...F('fashion_atelier_artisan'),
    desc: 'Master the atelier',
    category: 'progression',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Master the atelier',
  },
  {
    id: 'fashion_style_investor',
    name: 'Style Investor',
    ...F('fashion_style_investor'),
    desc: 'Invest in your style',
    category: 'progression',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Invest in your style',
  },
  {
    id: 'fashion_portfolio_tailor',
    name: 'Portfolio Tailor',
    ...F('fashion_portfolio_tailor'),
    desc: 'Tailor your portfolio',
    category: 'progression',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Tailor your portfolio',
  },
  {
    id: 'fashion_risk_couturier',
    name: 'Risk Couturier',
    ...F('fashion_risk_couturier'),
    desc: 'Take fashionable risks',
    category: 'progression',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Take fashionable risks',
  },
  {
    id: 'fashion_runway_ready',
    name: 'Runway Ready',
    ...F('fashion_runway_ready'),
    desc: 'Ready for the runway',
    category: 'progression',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Ready for the runway',
  },
  {
    id: 'fashion_final_runway',
    name: 'Final Runway Walked',
    ...F('fashion_final_runway'),
    desc: 'Walk the final runway',
    category: 'progression',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Walk the final runway',
  },
  {
    id: 'fashion_icon',
    name: 'Fashion Legend',
    ...F('fashion_icon'),
    desc: 'Conquered The Icon in District III',
    category: 'progression',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Conquered The Icon in District III',
  },
  {
    id: 'fashion_encore',
    name: 'Encore Collection',
    ...F('fashion_encore'),
    desc: 'Create an encore collection',
    category: 'progression',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Create an encore collection',
  },

  // Batch 2 — Boss Battles (12 badges)
  // Tiers: common/uncommon/rare/epic/uncommon/rare/epic/rare/rare/epic/rare/legendary
  {
    id: 'fashion_critic_1',
    name: 'Critic Conquered I',
    ...F('fashion_critic_1'),
    desc: 'Defeat your first critic',
    category: 'boss_battles',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Defeat your first critic',
  },
  {
    id: 'fashion_critic_2',
    name: 'Critic Conquered II',
    ...F('fashion_critic_2'),
    desc: 'Defeat the second critic',
    category: 'boss_battles',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Defeat the second critic',
  },
  {
    id: 'fashion_critic_3',
    name: 'Critic Conquered III',
    ...F('fashion_critic_3'),
    desc: 'Defeat the third critic',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Defeat the third critic',
  },
  {
    id: 'fashion_critic_silencer',
    name: 'Critic Silencer',
    ...F('fashion_critic_silencer'),
    desc: 'Silence all critics',
    category: 'boss_battles',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Silence all critics',
  },
  {
    id: 'fashion_boutique_champ',
    name: 'Boutique Champion',
    ...F('fashion_boutique_champ'),
    desc: 'Champion of the boutique',
    category: 'boss_battles',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Champion of the boutique',
  },
  {
    id: 'fashion_atelier_victor',
    name: 'Atelier Victor',
    ...F('fashion_atelier_victor'),
    desc: 'Victorious in the atelier',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Victorious in the atelier',
  },
  {
    id: 'fashion_runway_conqueror',
    name: 'Runway Conqueror',
    ...F('fashion_runway_conqueror'),
    desc: 'Conquer the runway',
    category: 'boss_battles',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Conquer the runway',
  },
  {
    id: 'fashion_director',
    name: 'Fashion Director',
    ...F('fashion_director'),
    desc: 'Direct the fashion world',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Direct the fashion world',
  },
  {
    id: 'fashion_icon_dethroned',
    name: 'Icon Dethroned',
    ...F('fashion_icon_dethroned'),
    desc: 'Dethrone the fashion icon',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Dethrone the fashion icon',
  },
  {
    id: 'fashion_flawless_runway',
    name: 'Flawless Runway',
    ...F('fashion_flawless_runway'),
    desc: 'A flawless runway show',
    category: 'boss_battles',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'A flawless runway show',
  },
  {
    id: 'fashion_speed_stylist',
    name: 'Speed Stylist',
    ...F('fashion_speed_stylist'),
    desc: 'Style at lightning speed',
    category: 'boss_battles',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Style at lightning speed',
  },
  {
    id: 'fashion_grand_finale',
    name: 'Grand Finale',
    ...F('fashion_grand_finale'),
    desc: 'Defeated all three Fashion Critics',
    category: 'boss_battles',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Defeated all three Fashion Critics',
  },

  // Batch 3 — Mastery (10 badges)
  // Tiers: common/uncommon/rare/epic/legendary/uncommon/rare/epic/epic/legendary
  {
    id: 'fashion_first_piece',
    name: 'First Piece',
    ...F('fashion_first_piece'),
    desc: 'Unlock your first wardrobe item',
    category: 'mastery',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_wardrobe_builder',
    name: 'Wardrobe Builder',
    ...F('fashion_wardrobe_builder'),
    desc: 'Start building your wardrobe',
    category: 'mastery',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_wardrobe_curator',
    name: 'Wardrobe Curator',
    ...F('fashion_wardrobe_curator'),
    desc: 'Curate a sophisticated wardrobe',
    category: 'mastery',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_full_wardrobe',
    name: 'Full Wardrobe',
    ...F('fashion_full_wardrobe'),
    desc: 'Complete your wardrobe',
    category: 'mastery',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_haute_couture',
    name: 'Haute Couture',
    ...F('fashion_haute_couture'),
    desc: 'Reach the highest fashion level',
    category: 'mastery',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_haute_couture_2',
    name: 'Haute Couture II',
    ...F('fashion_haute_couture_2'),
    desc: 'Master the highest fashion level',
    category: 'mastery',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_perfect_styling',
    name: 'Perfect Styling',
    ...F('fashion_perfect_styling'),
    desc: 'A clean, satisfying style',
    category: 'mastery',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_style_streak',
    name: 'Style Streak',
    ...F('fashion_style_streak'),
    desc: 'Keep your style streak going',
    category: 'mastery',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_no_malfunctions',
    name: 'No Wardrobe Malfunctions',
    ...F('fashion_no_malfunctions'),
    desc: 'Zero failed quizzes',
    category: 'mastery',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },
  {
    id: 'fashion_platinum_label',
    name: 'Platinum Label',
    ...F('fashion_platinum_label'),
    desc: 'Perfect score across all domains',
    category: 'mastery',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Keep pushing your skills further...',
  },

  // Batch 4 — Streaks (10 badges)
  // Tiers: common/uncommon/rare/epic/legendary/common/uncommon/rare/epic/legendary
  {
    id: 'fashion_streak_3',
    name: 'Style Starter',
    ...F('fashion_streak_3'),
    desc: 'Maintained a 3-day learning streak',
    category: 'streaks',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_dedicated',
    name: 'Dedicated Fashionista',
    ...F('fashion_dedicated'),
    desc: '7-day learning streak',
    category: 'streaks',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_runway_regular',
    name: 'Runway Regular',
    ...F('fashion_runway_regular'),
    desc: '14-day learning streak',
    category: 'streaks',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_obsessed',
    name: 'Fashion Obsessed',
    ...F('fashion_obsessed'),
    desc: '30-day streak',
    category: 'streaks',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_eternal_elegance',
    name: 'Eternal Elegance',
    ...F('fashion_eternal_elegance'),
    desc: '100-day streak',
    category: 'streaks',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_rising_star',
    name: 'Rising Star',
    ...F('fashion_rising_star'),
    desc: 'Earn 500 XP',
    category: 'streaks',
    tier: 'common',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_trendsetter',
    name: 'Trendsetter Status',
    ...F('fashion_trendsetter'),
    desc: 'Earn 1000 XP',
    category: 'streaks',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_elite_tier',
    name: 'Elite Tier',
    ...F('fashion_elite_tier'),
    desc: 'Earn 2000 XP',
    category: 'streaks',
    tier: 'rare',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_max_glamour',
    name: 'Max Glamour',
    ...F('fashion_max_glamour'),
    desc: 'Reach the XP cap',
    category: 'streaks',
    tier: 'epic',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },
  {
    id: 'fashion_style_royalty',
    name: 'Style Royalty',
    ...F('fashion_style_royalty'),
    desc: 'Become style royalty',
    category: 'streaks',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Keep showing up every day...',
  },

  // Batch 5 — Special (18 fashion badges)
  // Tiers: uncommon/uncommon/rare/rare/uncommon/uncommon/rare/uncommon/rare/common/epic/rare/rare/epic/legendary/uncommon/uncommon/common
  {
    id: 'fashion_quick_change',
    name: 'Quick Change',
    ...F('fashion_quick_change'),
    desc: 'Fast energy',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_marathon',
    name: 'Fashion Marathon',
    ...F('fashion_marathon'),
    desc: 'Full district in one session',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_speed_collection',
    name: 'Speed Collection',
    ...F('fashion_speed_collection'),
    desc: 'Domain speed-run',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_first_impression',
    name: 'First Impression',
    ...F('fashion_first_impression'),
    desc: 'Boss defeated on first try',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_well_tailored',
    name: 'Well-Tailored',
    ...F('fashion_well_tailored'),
    desc: 'No skill decay for 30 days',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_vintage_revival',
    name: 'Vintage Revival',
    ...F('fashion_vintage_revival'),
    desc: 'Old topics revisited',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_well_tailored_2',
    name: 'Well-Tailored II',
    ...F('fashion_well_tailored_2'),
    desc: 'No skill decay for 60 days',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_alterations',
    name: 'Alterations',
    ...F('fashion_alterations'),
    desc: 'Old topics revisited',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_comeback_couture',
    name: 'Comeback Couture',
    ...F('fashion_comeback_couture'),
    desc: 'Recovery from 3 consecutive losses',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_window_shopper',
    name: 'Window Shopper',
    ...F('fashion_window_shopper'),
    desc: 'Chic shop window',
    category: 'special',
    tier: 'common',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_all_styled',
    name: 'All Styled',
    ...F('fashion_all_styled'),
    desc: 'Styled every look across all Districts',
    category: 'special',
    tier: 'epic',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_label_collector',
    name: 'Label Collector',
    ...F('fashion_label_collector'),
    desc: '20 badges earned',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_badge_gal',
    name: 'Fashion Badge Gal',
    ...F('fashion_badge_gal'),
    desc: 'Collected 20 tiny badge dots',
    category: 'special',
    tier: 'rare',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_full_collection',
    name: 'Full Collection',
    ...F('fashion_full_collection'),
    desc: 'All domain badges earned',
    category: 'special',
    tier: 'epic',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_mogul',
    name: 'Fashion Mogul',
    ...F('fashion_mogul'),
    desc: '100 tiny badges spread',
    category: 'special',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_consultant',
    name: 'Style Consultant',
    ...F('fashion_consultant'),
    desc: '10 FINN questions asked',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_deep_dive',
    name: 'Deep Dive Darling',
    ...F('fashion_deep_dive'),
    desc: 'Deep Dive mode activated',
    category: 'special',
    tier: 'uncommon',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },
  {
    id: 'fashion_fitting_room',
    name: 'Fitting Room',
    ...F('fashion_fitting_room'),
    desc: 'Re-explanation requested',
    category: 'special',
    tier: 'common',
    secret: false,
    hintWhenLocked: "There's more to discover...",
  },

  // Batch 6 — Elite (5 badges) — all legendary
  {
    id: 'fashion_true_fashionista',
    name: 'True Fashionista',
    ...F('fashion_true_fashionista'),
    desc: 'True fashionista status',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'True fashionista status',
  },
  {
    id: 'fashion_couture_challenge',
    name: 'Couture Challenge',
    ...F('fashion_couture_challenge'),
    desc: 'Complete the couture challenge',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Complete the couture challenge',
  },
  {
    id: 'fashion_designer_diff',
    name: 'Designer Difficulty',
    ...F('fashion_designer_diff'),
    desc: 'Complete on designer difficulty',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Complete on designer difficulty',
  },
  {
    id: 'fashion_haute_mode',
    name: 'Haute Mode',
    ...F('fashion_haute_mode'),
    desc: 'Enable haute mode',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Enable haute mode',
  },
  {
    id: 'fashion_impossible',
    name: 'Impossible Elegance',
    ...F('fashion_impossible'),
    desc: 'Achieve impossible elegance',
    category: 'elite',
    tier: 'legendary',
    secret: false,
    hintWhenLocked: 'Achieve impossible elegance',
  },

  // Batch 7 — Secret (8 badges)
  // Tiers: legendary/rare/rare/uncommon/rare/epic/legendary/epic
  {
    id: 'fashion_birthday',
    name: 'Birthday Couture',
    ...F('fashion_birthday'),
    desc: 'Study on your birthday',
    category: 'secret',
    tier: 'legendary',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'fashion_midnight_runway',
    name: 'Midnight Runway',
    ...F('fashion_midnight_runway'),
    desc: 'Study after midnight',
    category: 'secret',
    tier: 'rare',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'fashion_dawn_collection',
    name: 'Dawn Collection',
    ...F('fashion_dawn_collection'),
    desc: 'Study at dawn',
    category: 'secret',
    tier: 'rare',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'fashion_weekend_vogue',
    name: 'Weekend Vogue',
    ...F('fashion_weekend_vogue'),
    desc: 'Study on weekends',
    category: 'secret',
    tier: 'uncommon',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'fashion_comeback_queen',
    name: 'Comeback Queen',
    ...F('fashion_comeback_queen'),
    desc: 'Return after a long break',
    category: 'secret',
    tier: 'rare',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'fashion_perfectionist',
    name: 'Perfectionist Tailor',
    ...F('fashion_perfectionist'),
    desc: 'Perfect score in all topics',
    category: 'secret',
    tier: 'epic',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'fashion_finns_muse',
    name: "FINN's Muse",
    ...F('fashion_finns_muse'),
    desc: 'FINN loves your style',
    category: 'secret',
    tier: 'legendary',
    secret: true,
    hintWhenLocked: null,
  },
  {
    id: 'fashion_true_devotion',
    name: 'True Devotion',
    ...F('fashion_true_devotion'),
    desc: '100 sessions completed',
    category: 'secret',
    tier: 'epic',
    secret: true,
    hintWhenLocked: null,
  },
];
